version: '3.8'
services:
  reverseproxy:
    image: jwilder/nginx-proxy
    container_name: reverseproxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro              
    networks:
      - net_bolsa
    restart: always
    privileged: true    
  
  angular:
    build: ../
    container_name: angular    
    volumes:
      - ../:/app
    environment: 
      - VIRTUAL_HOST=bolsatrabajo.com
    networks:
      - net_bolsa
    depends_on: 
      - reverseproxy              

networks:
  net_bolsa:
    name: net_bolsa
    driver: bridge